2019-10-11 09:45:16,956 ERROR: Exception on /file-upload [GET] [in /home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pratyush/workspace/microblog/app/routes.py", line 199, in file_upload
    return render_template('file-upload.html')
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pratyush/workspace/microblog/app/templates/file-upload.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/pratyush/workspace/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/pratyush/workspace/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/pratyush/workspace/microblog/app/templates/file-upload.html", line 8, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/wtf.html", line 200, in template
    {{ form.hidden_tag() }}
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-10-11 09:45:53,567 INFO: Microblog startup [in /home/pratyush/workspace/microblog/app/__init__.py:47]
2019-10-11 09:47:23,837 INFO: Microblog startup [in /home/pratyush/workspace/microblog/app/__init__.py:47]
2019-10-11 09:47:32,478 ERROR: Exception on /file-upload [POST] [in /home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pratyush/workspace/microblog/app/routes.py", line 196, in file_upload
    filename = secure_filename(form.data.file.filename)
AttributeError: 'dict' object has no attribute 'file'
2019-10-11 09:48:15,662 INFO: Microblog startup [in /home/pratyush/workspace/microblog/app/__init__.py:47]
2019-10-11 09:48:25,056 ERROR: Exception on /file-upload [POST] [in /home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pratyush/workspace/microblog/app/routes.py", line 197, in file_upload
    form.file.data.save('uploads/' + filename)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2799, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'uploads/3bxcxepbmvc31.jpg'
2019-10-11 09:48:59,225 INFO: Microblog startup [in /home/pratyush/workspace/microblog/app/__init__.py:47]
2019-10-11 09:49:02,706 ERROR: Exception on /file-upload [POST] [in /home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pratyush/workspace/microblog/app/routes.py", line 197, in file_upload
    form.file.data.save('uploads/' + filename)
  File "/home/pratyush/workspace/microblog/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2799, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'uploads/3bxcxepbmvc31.jpg'
2019-10-11 09:50:41,429 INFO: Microblog startup [in /home/pratyush/workspace/microblog/app/__init__.py:47]
